name: autofix.ci

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  autofix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9f698171ed81b15d1823a05fc7211befd50c8ae0 # v6.0.3

      - uses: pnpm/action-setup@c336a2788d9774dccfdeb4823a5058ccc9f07453 # v4.3.0
        with:
          version: 10.18.3

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install

      - run: pnpm lint:fix

      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "style: auto-fix lint issues"
